[package]
name = "xun_you"
version = "0.1.0"
description = "一个看小说的软件"
authors = ["ys928"]
license = "MIT"
repository = "https://github.com/ys928/XunYou"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "clipboard-all", "fs-all", "window-all", "global-shortcut-all", "dialog-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
window-shadows = "0.2.1"
bzip2 = "0.4"
md-5 = "0.10.5"
dirs = "5.0.1"
log = "0.4"
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
