[package]
name = "xunyou"
version = "2.0.2"
description = "xunyou"
authors = ["ys928"]
license = "MIT"
repository = "https://github.com/ys928/XunYou"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "clipboard-all", "fs-all", "window-all", "global-shortcut-all", "dialog-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
window-shadows = "0.2.2"
bzip2 = "0.4"
dirs = "5.0.1" 
regex = "1.10.4"
log = "0.4.21"
log4rs = "1.3.0"
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!! 
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
